export enum PrayersActionTypes {
  GET_PRAYERS = 'PRAYERS/GET_PRAYERS',
  CHANGE_PRAYER = 'PRAYERS/CHANGE_PRAYER',
  ADD_NEW_PRAYER = 'PRAYERS/ADD_NEW_PRAYER',
  DELETE_PRAYER = 'PRAYERS/DELETE_PRAYER',
}
